default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  - hooks:
      - args:
          - --maxkb=640
        id: check-added-large-files
      - id: end-of-file-fixer
      - exclude: .gitignore
        id: mixed-line-ending
      - exclude: .gitignore
        id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: conventional-pre-commit
    repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
  - hooks:
      - id: renovate-config-validator
    repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.385.0
